APP_NAME = "Sams Accounting Desktop"
APP_VERSION = "v1.0.3"
DEFAULT_TALLY_URL = "http://127.0.0.1:9000"
TIMEOUT_SECONDS = 8
PURCHASE_RECO_TIMEOUT_SECONDS = 45
UPDATE_MANIFEST_URL = "https://sams-accounting-services.vercel.app/desktop-update.json"
UPDATE_CHECK_TIMEOUT_SECONDS = 5
TERMS_VERSION = "2026-08-27"
TERMS_URL = "https://thejishu.in/terms.html"
PRIVACY_URL = "https://thejishu.in/privacy.html"
SUPPORT_EMAIL = "sameermansurisam@gmail.com"
SUPPORT_PHONE = "+91 98269 05008"
TRIAL_DAYS = 14
