from __future__ import annotations

from sams_accounting_desktop.config import (
    APP_NAME,
    PRIVACY_URL,
    SUPPORT_EMAIL,
    SUPPORT_PHONE,
    TERMS_URL,
    TERMS_VERSION,
)


TERMS_OF_USE = f"""TERMS OF USE
Effective date: {TERMS_VERSION}

1. Agreement
By installing, activating, or using {APP_NAME}, you agree to these Terms of Use. If you do not agree, do not activate or use the software.

2. Product and licence
The software provides local accounting workflow tools, including statement parsing, reconciliation, sales preparation, and Tally integration. A valid licence or active trial grants a limited, non-exclusive, non-transferable right to use the software for lawful internal business purposes. You must not resell, reverse engineer, bypass licence controls, or use the software for unlawful activity.

3. User responsibility and review
Accounting, tax, GST, ledger, voucher, and reconciliation outputs are automation assistance, not legal, tax, audit, or professional accounting advice. You are responsible for reviewing source documents, ledger mappings, amounts, taxes, voucher dates, narrations, and every entry before posting or relying on it. Maintain independent backups of Tally data and business records.

4. Tally and third-party services
Tally is a third-party product. The Jishu IT Solution is not affiliated with or endorsed by Tally Solutions. Availability and behaviour of Tally, Windows, GitHub downloads, and other third-party systems are outside our control and may change.

5. Updates and support
Updates may add, change, or remove features and may be required for security or compatibility. Support is provided using the contact details below, subject to the applicable purchase, subscription, or written commercial agreement.

6. Fees, cancellation, and refunds
Fees, taxes, subscription duration, cancellation, and refund terms are governed by the order, invoice, or written commercial agreement and applicable consumer law. Nothing in these Terms limits rights that cannot lawfully be excluded.

7. Availability and warranties
The software is provided on an "as available" basis. We aim for reliable operation but do not guarantee uninterrupted or error-free service, compatibility with every statement format or Tally configuration, or that automated output will always be accurate.

8. Liability
To the extent permitted by law, The Jishu IT Solution is not liable for indirect or consequential loss, loss of profits, corrupted or incorrect accounting records, penalties, or business interruption arising from unreviewed output, unsupported formats, third-party failures, or failure to maintain backups. This does not exclude liability that cannot lawfully be excluded.

9. Suspension and termination
Access may be suspended or terminated for licence abuse, unlawful use, security threats, or material breach. On termination, you must stop using the software. Provisions intended to survive termination continue to apply.

10. Governing law and grievances
These Terms are governed by the laws of India. Courts and consumer forums with jurisdiction under applicable law may hear disputes. Please first contact us so we can attempt to resolve the issue.

Support and grievance contact
The Jishu IT Solution
Email: {SUPPORT_EMAIL}
Phone: {SUPPORT_PHONE}
Online version: {TERMS_URL}
"""


PRIVACY_POLICY = f"""PRIVACY POLICY
Effective date: {TERMS_VERSION}

1. Scope
This Privacy Policy explains how {APP_NAME}, provided by The Jishu IT Solution, handles personal data and accounting files.

2. Data handled by the desktop app
Activation data: name, email address or mobile number, licence or trial status, consent version, and acceptance timestamps.
Accounting data: bank statements, GST purchase files, sales files, ledger names, voucher previews, and reconciliation results selected or generated by you.
Technical data: app version, update-check status, local Tally URL, and error messages shown within the app.

3. Purpose
We process activation data to verify access, maintain consent records, provide support, and prevent licence abuse. Accounting data is processed to provide the workflow you select. Technical data is used for compatibility, updates, troubleshooting, and security.

4. Local processing and network connections
Activation settings are stored locally in your Windows application-data folder. Selected accounting files are processed locally by the desktop app. The app connects to Tally only at the local URL you configure, normally http://127.0.0.1:9000. The update checker contacts our published update manifest, and an installer download opens GitHub only when you choose it. The current desktop build does not include advertising trackers or analytics and does not automatically upload accounting files to our servers.

5. Consent and choice
Activation requires you to separately accept the Terms of Use and this Privacy Policy. You may decline and stop activation. You may withdraw consent by contacting us and deleting the local settings file or uninstalling the app; withdrawal does not affect processing already lawfully completed.

6. Retention and deletion
Local activation settings remain until you remove them, reset the app, or uninstall and delete its application-data folder. Files you select and exports you create remain where you store them. Support communications are retained only as reasonably necessary for support, legal, security, and accounting obligations.

7. Sharing
We do not sell personal data. Data may be shared with service providers only when needed to provide a requested service, comply with law, protect rights or security, or complete a business transaction with appropriate safeguards. Local accounting files are not shared by the current desktop build unless you independently transmit them.

8. Security
We use reasonable technical and organisational safeguards, including local processing and signed licence validation. No system is completely secure. Protect your Windows account, backups, Tally access, exported files, and licence credentials.

9. Your rights and grievances
Subject to applicable law, you may request information, correction, completion, erasure, consent withdrawal, or grievance handling regarding personal data we control. We may need to verify your identity before acting.

10. Children
The software is intended for business users and is not directed to children.

11. Changes
Material policy changes will use a new consent version. The app may require renewed acceptance before continued activation.

Privacy and grievance contact
The Jishu IT Solution
Email: {SUPPORT_EMAIL}
Phone: {SUPPORT_PHONE}
Online version: {PRIVACY_URL}
"""
